### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by krosoftware** [syncfusion/ej2#1]
Hello
I did 
npm install
and then
npm run build
but there are some errors:
`c:\web\ej>npm run build

> @syncfusion/ej2@1.0.0 build c:\web\ej
> gulp build

[11:14:02] Using gulpfile c:\web\ej\gulpfile.js
[11:14:02] Starting 'scripts'...
[11:14:02] Finished 'scripts' after 596 ms
[11:14:02] Starting 'styles'...
error TS2688: Cannot find type definition file for 'jasmine'.
error TS2688: Cannot find type definition file for 'jasmine-ajax'.
error TS2688: Cannot find type definition file for 'requirejs'.
[11:14:07] TypeScript: 3 options errors
[11:14:07] TypeScript: emit succeeded (with errors)
[11:14:07] Finished 'styles' after 4.97 s
[11:14:07] Starting 'build'...
[11:14:07] Finished 'build' after 6.42 us`

also, is there any ready demos (to download)?
Thank you

**Comment by SridharSathaSivam** [comment]
Hi Krosoftware,

Thanks for your interest in Essential JS 2. We have fixed the compilation issue, please pull the latest source and try build command again.

Currently our demo source is not available in GitHub repository. We have planned to publish our samples in GitHub on or before June 15, 2017. 

Until then you can use our documentation to view snippets and run them in plunker. Each plunker is a complete runnable sample for that particular component.

Documentation link: http://ej2.syncfusion.com/documentation/

Please find the Plunker link for Grid.
http://plnkr.co/edit/iE8KGOP3VA0KVMLW7XuE?p=preview

Thanks,
Sridhar S

**Comment by krosoftware** [comment]
OK will do, thank you.

**Comment by SridharSathaSivam** [comment]
Hi Krosoftware,

Sample are now available at github repository.

Pure JS Demo Repository :  https://github.com/syncfusion/ej2-samples/tree/v1.0.0-preview

Thanks,
Sridhar S

**Comment by krosoftware** [comment]
Awesome, Thank you so much!
