### ISSUE TITLE
Pivot Grid

### ISSUE THREAD

**Issue by nm-a** [syncfusion/ej2#10]
Dear Team,
Thank you for the nice toolkit, I fee the Vision / Roadmap is very nice. Will there be any possibility to include Pivot Grid to the controls list. The Tree-Grid & Pivot-Grid's are very useful to play with data in run-time.

thank you
-nm

**Comment by pavithra95subramaniam** [comment]
Hi Nmreddy,

We already have TreeGrid and PivotGrid in our internal roadmap of Essential JS 2. These are tentatively planned to be available in mid of 2018.   
   
Regards, 
Pavithra S.

**Comment by nm-a** [comment]
thank you
