### ISSUE TITLE
Internationalization doesn't work after change form version 15.4.17 to version 15.4.20

### ISSUE THREAD

**Issue by j-nord** [syncfusion/ej2#11]
Hi,

after change to version 15.4.17 to version 15.4.20 the german cultur doesn't wok.

code from the app.module.ts:

```
import { loadCldr, setCulture, setCurrencyCode } from '@syncfusion/ej2-base';
loadCldr(
    require('cldr-data/main/de/ca-gregorian.json'),
    require('cldr-data/main/de/timeZoneNames.json'),
    require('cldr-data/main/de/numbers.json'),
    require('cldr-data/supplemental/numberingSystems.json'),
    require('cldr-data/main/de/currencies.json')
)

// Syncfusion
setCulture("de");
setCurrencyCode('EUR');
```

Why??

Regards

j.nord

**Comment by Mydeen-SN** [comment]
Hi j-nord,

We have validated the reported issue and we are unable to reproduce the issue on our side. We have checked the [ej2-angular-setCulture](https://github.com/SyncfusionSamples/ej2-angular-setCulture) project with latest Essential JS 2 packages and also we have prepared the plunker sample for the same.

Plunker sample: http://plnkr.co/edit/cgDdntG3UMwIkSXTHpQp?p=preview 

If you are still facing the same issue again, please provide us the sample or modify the given sample with issue replication steps.

Regards,
Mydeen S N

**Comment by j-nord** [comment]
Hi,

thank you for the answer. But we doesn't work with system.js, we work with webpack 3.10.0. and after change the Version the culture doesn't run.

Regards

j.nord

**Comment by Mydeen-SN** [comment]
Hi J-nord,

We have tested the [ej2-angular-setCulture](https://github.com/SyncfusionSamples/ej2-angular-setCulture) with the webpack version 3.10.0 and  latest Essential JS 2 components but we are unable to reproduce the issue. Could you please share the sample if  possible or modify given sample for reproducing the issue.

Regards,
Mydeen S N

**Comment by j-nord** [comment]
we need realistic projects. We can not import the cldr-data "json" module into typescript!

We have net core in the backend and angular 5.1 in front-end. Under js1 it works and with Version 15.4.17 it run also.

We can not write an rewrite our programs complete and upload gread Project. Then we have the wrong tool!

A afraid customer!

**Comment by Mydeen-SN** [comment]
Hi J-nord,

A support incident has been created under your account to resolve the issue through web meeting. Please log on to our support website to check for further updates.

https://www.syncfusion.com/Account/Logon?ReturnUrl=/support/directtrac 

Regards,
Mydeen S N

**Comment by j-nord** [comment]
Hi Mydeen,

we have changed to version 16.1.32. We have clean the node cache "npm cache clear --force". We have deleted all files in the node_module directory. And then reinstalled all the modules -> npm install.

...and then we have the same problem again !!!

The internationalization does not work properly !

Our project.json:

{
  "name": "angular-webpack-visualstudio",
  "version": "1.0.0",
  "description": "An Angular VS template",
  "main": "wwwroot/index.html",
  "author": "",
  "license": "ISC",
  "repository": {
    "type": "git",
    "url": "https://github.com/damienbod/Angular2WebpackVisualStudio.git"
  },
  "scripts": {
    "ngc": "ngc -p ./tsconfig-aot.json",
    "build:dev": "set NODE_ENV=development && webpack",
    "build:prod": "ngc -p ./tsconfig-aot.json && set NODE_ENV=production && webpack",
    "build:dev-p": "set NODE_ENV=development && webpack --progress --color",
    "build:prod-p": "ngc -p ./tsconfig-aot.json && set NODE_ENV=production && webpack --progress --color",
    "publish-for-iis": "npm run build-production && dotnet publish -c Release",
    "test": "karma start"
  },
  "dependencies": {
    "@angular/animations": "5.2.9",
    "@angular/common": "5.2.9",
    "@angular/compiler": "5.2.9",
    "@angular/compiler-cli": "5.2.9",
    "@angular/core": "5.2.9",
    "@angular/forms": "5.2.9",
    "@angular/http": "5.1.0",
    "@angular/platform-browser": "5.2.9",
    "@angular/platform-browser-dynamic": "5.2.9",
    "@angular/platform-server": "5.2.9",
    "@angular/router": "5.2.9",
    "@angular/upgrade": "5.2.9",
    "@ng-bootstrap/ng-bootstrap": "1.0.1",
    "@syncfusion/ej2-base": "16.1.32",
    "@syncfusion/ej2-ng-base": "16.1.32",
    "@syncfusion/ej2-ng-buttons": "16.1.32",
    "@syncfusion/ej2-ng-calendars": "16.1.32",
    "@syncfusion/ej2-ng-dropdowns": "16.1.32",
    "@syncfusion/ej2-ng-grids": "16.1.32",
    "@syncfusion/ej2-ng-inputs": "16.1.32",
    "@syncfusion/ej2-ng-navigations": "16.1.32",
    "@syncfusion/ej2-ng-popups": "16.1.32",
    "aspnet-webpack": "2.0.3",
    "bootstrap": "4.0.0",
    "classlist.js": "^1.1.20150312",
    "core-js": "2.5.3",
    "file-saver": "^1.3.3",
    "font-awesome": "4.7.0",
    "fs": "0.0.1-security",
    "ie-shim": "~0.1.0",
    "intl": "^1.2.5",
    "jquery": "3.3.1",
    "json2csv": "^3.8.1",
    "moment": "2.19.4",
    "ng2-archwizard": "2.1.0",
    "ngx-openlayers": "0.6.10",
    "popper.js": "1.12.9",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.5.5",
    "tether": "1.4.0",
    "web-animations-js": "^2.3.1",
    "webpack-node-externals": "^1.6.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ngtools/webpack": "1.9.0",
    "@types/file-saver": "0.0.1",
    "@types/jasmine": "2.5.47",
    "@types/jquery": "^2.0.45",
    "@types/node": "7.0.13",
    "angular-router-loader": "0.8.0",
    "angular2-template-loader": "0.6.2",
    "awesome-typescript-loader": "3.4.1",
    "cldr-data": "32.0.1",
    "clean-webpack-plugin": "^0.1.16",
    "concurrently": "^3.4.0",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.0",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "^0.11.1",
    "html-webpack-plugin": "2.30.1",
    "jasmine-core": "2.5.2",
    "json-loader": "0.5.7",
    "node-sass": "^4.5.2",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.6.1",
    "sass-loader": "6.0.6",
    "source-map-loader": "0.2.3",
    "style-loader": "0.19.0",
    "to-string-loader": "1.1.5",
    "ts-helpers": "^1.1.2",
    "ts-loader": "2.3.7",
    "tslint": "^5.1.0",
    "tslint-loader": "^3.5.2",
    "typescript": "2.5.2",
    "url-loader": "^0.5.8",
    "webpack": "3.11.0",
    "webpack-dev-server": "2.11.1",
    "webpack-hot-middleware": "2.21.2",
    "webpack-parallel-uglify-plugin": "1.0.2"
  }
}

We hope for a solution!

Regards

j.nord

**Comment by j-nord** [comment]
**The npm download Version 16.1.28 doesn't work with Internationalization.**

When we recovert a older directory of Version 16.1.28 from a backup, the Internationalization works. When we install the Version over npm download it doesn't work.

**We searched one day for errors to find out that there is a broken version on the npm server. That's the second time already. What's going on there??**

Regards
j.nord
