### ISSUE TITLE
Contains Filter operator creates query with "substringof " does not support in web API2 OData

### ISSUE THREAD

**Issue by WASIT412** [syncfusion/ej2#14]
Contains Filter operator creates query with "substringof " which does not support in web API2 OData
below is my url which is not working:
http://localhost:51793/api/getCustomers/?$inlinecount=allpages&$filter=substringof(%27st%27,Code)&$orderby=Code&$skip=0&$top=12 

Actual url  should have been like :
http://localhost:51793/api/agetCustomers/?$inlinecount=allpages&$filter=contains(%27st%27,Code)&$orderby=Code&$skip=0&$top=12

**Comment by jmfarook** [comment]
Hi @WASIT412 
 To use ODataV4 Adaptor in your sample, it supports to register V4 functionality and its queries.

Thanks,
Farook
