### ISSUE TITLE
Filter one column in grid

### ISSUE THREAD

**Issue by sontn94** [syncfusion/ej2#16]
Hi, supporters,
I just wanna filter only "ShipCity" column, and other columns do not filter, but it not has the option to support that. 

let grid: Grid = new Grid({
    dataSource: data,
    allowFiltering: true,
    columns: [
        { field: 'OrderID.text', headerText: 'Order ID', textAlign: 'right', width: 100 },
        { field: 'CustomerID', headerText: 'Customer ID', width: 120 },
        { field: 'ShipCity', headerText: 'Ship City', width: 100 },
        { field: 'ShipName', headerText: 'Ship Name', width: 100 }
    ],
    height: 273
});

Please show me what I need to do to implement filtering in this case, many thanks

**Comment by Madhust** [comment]
@sontn94, Please set `columns.allowFiltering` property as false for other columns.

For more information, please check the below note from the help link.

http://ej2.syncfusion.com/15.4.23/documentation/grid/filtering.html?lang=typescript

> To disable filtering for a particular column, set columns.allowFiltering to false.

**Sample:** http://plnkr.co/edit/rzsEymO3XvNvPnJGA3bd?p=preview

**Comment by sontn94** [comment]
Thank for your support! <3
