### ISSUE TITLE
Mobile preview

### ISSUE THREAD

**Issue by krosoftware** [syncfusion/ej2#19]
Hello
how to test the demo on mobile device?
For example, if I run this demo:
http://ej2.syncfusion.com/15.4.23/javascript/demos/samples/grid/autowrap/index.html
I see example like in desktop browser but small. Does it not need to adopt to mobile device screen?

**Comment by ajithr** [comment]
Hi @krosoftware ,

We have resolved the view port problem in the new window option of our demo samples by adding below meta tag.

`<meta name="viewport" content="width=device-width, initial-scale=1.0">`

The latest sample browser with new window sample is working now. Please refer the below link for further details.

http://ej2.syncfusion.com/16.1.24/javascript/demos/samples/grid/autowrap/index.html

Regards,
Ajith R
