### ISSUE TITLE
Grid - Boolean column and Menu filter - Filter value bug

### ISSUE THREAD

**Issue by 1dot44mb** [syncfusion/ej2#20]
When column type is boolean and filter type is Menu, filtering values do not appear as True, False. Instead, [Object object] appears and filtering does not work.
Thanks.

**Comment by isuriya-r39** [comment]
We are glad to announce that our (v 16.4.28) release is rolled out successfully and In that release, we have included  the fix for “Boolean column displays the filtering option as [object object ] while using DataManager”  issue.

**Comment by 1dot44mb** [comment]
Thanks. How can i downoad 16.4.28? Release page and EJ2 website still shows 16.1.024 as latest release.

**Comment by isuriya-r39** [comment]
EJ2 patch release will not be included in our site. You can get the release information such as change log from the GitHub itself.

**Comment by isuriya-r39** [comment]
EJ2 patch release will not be included in our site. 


For updating the package please use this below command 
 
1.	Using the “npm update” command.
 
•	This will update all our listed packages and also will install missing packages too.  
•	Updating package we need to  change the syncfusion package version in package.json file. Or use ( * ) to get latest package.
•	Please refer the below link for your reference:
 
Link: https://docs.npmjs.com/cli/update

**Comment by 1dot44mb** [comment]
Updating to 16.1.29 solved the issue. Thanks.
