### ISSUE TITLE
.net standard support

### ISSUE THREAD

**Issue by fileman** [syncfusion/ej2#23]
Since asp.net core 2.0 have added possibility to have razor ui view / pages in separate .net standard class library, have you planned release of .netstandard version of ej2 controls library?

**Comment by bharathm03** [comment]
@fileman Thanks for the information. Yes, we have planned to give Syncfusion.EJ2 nuget package as .netstandard library. This will be available by our upcoming Essential Studio Vol 2, 2018 release. This is expected to be available by mid of May, 2018. 

Let me know if you have any concerns.

**Comment by ajithr** [comment]
Hi @fileman ,

Thanks for your patience.

We are glad to let you know that, now the Essential JS2 have the support for .netstandard version of ASP.NET Core and it is available from 16.2.0.41 version of Essential Studio.

Please find the below NuGet package for further details.
https://www.nuget.org/packages/Syncfusion.EJ2/

Regards,
Ajith R

**Comment by fileman** [comment]
thanks!

**Comment by danielmeza** [comment]
@ajithr  Any documentation or get starter ghide ?

**Comment by ajithr** [comment]
Hi @danielmeza ,

Please find the below link for the getting started documentation of Essential JS 2 for ASP.NET Core.

https://ej2.syncfusion.com/aspnetcore/documentation/getting-started/

Regards,
Ajith R
