### ISSUE TITLE
Right To Left Support - RTL

### ISSUE THREAD

**Issue by gmareater** [syncfusion/ej2#26]
Hi
I was checking your components, and I noticed must of them (mainly grid) does not support RTL,
I checked your road map and you did not mention RTL in the upcoming release, So do you have any plan to support RTL? 

thanx

**Comment by renjith123** [comment]
Hi gmareater,

We are glad to inform you that we already have support for RTL in EJ2 Grid. To enable RTL in Grid we suggest you to set the “enableRtl” property of Grid as true. We have created a simple plunker sample with RTL enabled in it. Please refer the sample link below,

Sample : https://plnkr.co/edit/nrOoBirTG1e5WokHLqrm?p=preview

Documentations : 
https://ej2.syncfusion.com/16.1.24/documentation/grid/api-grid.html?lang=typescript#enablertl
https://ej2.syncfusion.com/16.1.32/documentation/base/right-to-left.html?lang=typescript

Regards,
Renjith Singh Rajendran.
