### ISSUE TITLE
SideBar

### ISSUE THREAD

**Issue by krosoftware** [syncfusion/ej2#4]
Hello
do you have plans to include Drawer (http://js.syncfusion.com/demos/web/#!/office-365/navigationdrawer/defaultfunctionalities)
Thank you.

**Comment by bharathm03** [comment]
@krosoftware Thank you for your interest in Syncfusion. We will consider your request for drawer control and internally increased the priority for this control. This is estimated to be available by end of September.

Thanks
Bharath

**Comment by krosoftware** [comment]
Awesome, thank you.
I'm looking long time for single framework for all devices (desktop/mobile etc). and Drawer control is one of the components which are "must"..
Your new framework looks great and I'm looking forward for your progress 👍

**Comment by bharathm03** [comment]
@krosoftware We are happy to let you know that, we have rolled out the Sidebar component preview. I suggest you evaluate our sidebar component's samples and documentations and share your feedback on this.

Samples : https://ej2.syncfusion.com/16.1.24/demos/#/material/sidebar/default
Documentation: http://ej2.syncfusion.com/16.1.24/documentation/sidebar/?lang=typescript
