### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by krosoftware** [syncfusion/ej2#5]
You created great example for SyncFusion JavaScript version:
http://js.syncfusion.com/demos/web/dashboard/webmail/default.html
is it possible to prepare such example for ej2, please?
What I mean is to create example where all components are responsive and visible on all devices, something like http://guillaumebiton.github.io/HackerNews7/
Thank you!

**Comment by bharathm03** [comment]
@krosoftware Currently we don't have webmail like example. However our sample browser application is responsive and visible on all devices. 

http://ej2.syncfusion.com/demos/
and its source available in this repo
https://github.com/syncfusion/ej2-samples/tree/v1.0.0-preview 

In further, we are also working on a Expense Analysis demo app which is a modern version from our [JavaScript](http://js.syncfusion.com/demos/web/dashboard/expenseanalysis/default.html) demo. I will check the current development status of it and update you by tomorrow.

Thanks
Bharath

**Comment by krosoftware** [comment]
OK thank you.
what I mean't is to have real responsive demo - your [JavaScript](http://js.syncfusion.com/demos/web/dashboard/expenseanalysis/default.html) example is OK but here are some ideas:
- please add some Drawer control at the left (as on image below) which is visible on desktop (on large monitors your JS example take less then 50% of screen. What I mean (of course, if it is possible) that Drawer on left side is displayed on large devices and minimised on smaller devices;
- if possible, please add some sidebar on right side (as you can see on image below) , too (always visible on larger devices and hidden on smaller devices - or hidden/visible on request). With other words - something like this one: http://guillaumebiton.github.io/HackerNews7/
or your http://js.syncfusion.com/demos/web/dashboard/webmail/default.html
that's great examples of screen usage - it should only be usable on mobile devices - that's something I meant that you will do with new framework.
Thank you for your consideration.

![image](https://user-images.githubusercontent.com/8056218/27385378-c044bd2a-5692-11e7-9f71-2b590487f54f.png)

**Comment by bharathm03** [comment]
@krosoftware Please find the development version of expense analysis sample that we are working on. This features custom sidebar at left with auto hide behavior on mobile however it is lacking sidebar at right side. 

[Expense-demo.zip](https://github.com/syncfusion/ej2/files/1094955/Expense-demo.zip) 

To run sample, extract and use the follow the command line scripts
```shell
npm install -g gulp
npm install
gulp serve
```

Hope it helps

Thanks 
Bharath

**Comment by krosoftware** [comment]
OK will do, thank you so much.
