### ISSUE TITLE
Vue.js support & Dialogs vertical position

### ISSUE THREAD

**Issue by iang0ld** [syncfusion/ej2#6]
I have noticed that not specifying a width results in the width being set to the width of the contain which is great.

However the vertical positoin apprears to be set to something fixed.  can I suggest that the default (i.e. no height provided results in the dialog being centered vertically.  FYI an option to make it full height of the container would also be useful.

**Comment by soundarapandianr** [comment]
@iang0ld, Thanks for your interest in Essential JS 2. In Dialog, we have defined [width](http://ej2.syncfusion.com/documentation/dialog/api-dialog.html#width-string---number) as 100% by default, so it occupies full width to its container. But we have defined [height](http://ej2.syncfusion.com/documentation/dialog/api-dialog.html#height-string---number) as ‘auto’ by default, so it will render based on content’ height. We need to set height as 100% to achieve your requirement “Dialog height should occupy full container height”.

Sample link:
http://plnkr.co/edit/YuKxCGa7by263NYcLoUD?p=preview 

Thanks
Soundara Pandian R

**Comment by iang0ld** [comment]
Thank you. Yes I am very interested.  I will be using with  vue when available. Questions . So how can I center a dialog vertically?



Sent from my Samsung device


-------- Original message --------

**Comment by soundarapandianr** [comment]
@iang0ld, already we have the plan in our [Roadmap](https://www.syncfusion.com/products/essential-js2) to provide support for Vue.js framework, and it will be available in the second quarter of next year.

And for the vertical alignment of Dialog, you can use the [position](http://ej2.syncfusion.com/documentation/dialog/api-dialog.html#position-positiondata) property which will position the Dialog inside the target container based on 9 predefined positions. 

Please refer the sample: http://plnkr.co/edit/zWZzqR5KltUb8eEb8bhx?p=preview 

For more details about Dialog positioning, please refer the below documentation link:
http://ej2.syncfusion.com/documentation/dialog/getting-started.html#positioning 

Thanks
Soundara Pandian R

**Comment by iang0ld** [comment]
Thank you for the heads up on timing on vue.js support.

And think you for making me aware of the position property. As usually your controls are extremely well thought out and have all the feature real develops need.

If I can help review or test anything for you let me know.

**Comment by iang0ld** [comment]
Soundara,

I know I am pushing the friendship, but I am trying to add typescript to an MVC 5 project in VS 2017 so I can start using ej2 and it is a nightmare.

Are you able to point me a resource or example solution that may help?

Yours
Ian

**Comment by iang0ld** [comment]
Alternatively, do you have a basic example of using the library from standard javacript?

**Comment by ajithr** [comment]
Hi @iang0ld ,

We are glad to let you know that, now the Essential JS 2 have the Vue.js framework support and it is available from 16.2.0.41 version of Essential Studio.

Please find the below links for further details.
**Product page:** https://www.syncfusion.com/products/vue/
**Demos:** https://ej2.syncfusion.com/home/vue.html
**Documentation:** https://ej2.syncfusion.com/vue/documentation/

Regards,
Ajith R

**Comment by iang0ld** [comment]
Thank you so much. I'll get right into it.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by bharathm03** [comment]
@iang0ld I have created a new issue for tracking Filter builder request https://github.com/syncfusion/ej2/issues/28. Our team will update you the response for it there. So, I'm closing this issue.

**Comment by iang0ld** [comment]
Thank you



Sent from my Samsung Galaxy smartphone.


-------- Original message --------
