### ISSUE TITLE
Visual Studio 2017 15.3 integration

### ISSUE THREAD

**Issue by iang0ld** [syncfusion/ej2#7]
I would like to start using ej2 in an existing project.  I would therefore like to generate js files so I can use this library without typescript as we progesively update the site.  How can I do this can I use the umd files? Do I need to add the ts file and build inside VS2017?   If I use ts for new pages how do I reference tj2?

Thanks

**Comment by SridharSathaSivam** [comment]
Hi @iang0ld,

Thanks for your interest in Essential JS 2, We are providing `global` file which you can refer directly to your application.  We have created github sample to use EJ2 global file. Find sample in below link.

https://github.com/SridharSathaSivam/ej2-global 

Thanks,
Sridhar S

**Comment by iang0ld** [comment]
Hi Sridhar,

Fantastic.  Got it!

You guys are great.

Thanks
Ian
