### ISSUE TITLE
Pure Javascript version size?

### ISSUE THREAD

**Issue by iang0ld** [syncfusion/ej2#8]
We would like to use this library in multipage MVC. I am looking mininise the javascript loaded. eg. one page may only need the toolbar, another may onlu need buttons and imputs.

I and guessing that the /dist/es6 diretories include the javascript for the individual components and that the can be loaded one after the other?  Is this correct?  If so, do you have the dependancies listed anythere or are their none?  For eg does the dropdown depend on popups?

**Comment by SridharSathaSivam** [comment]
Hi @iang0ld,


Thanks for your interest in Essential JS 2, We can use bundler to achieve your requirement. So bundler will take care of component dependencies and you can get minimized javascript.

I have created a demo in Github based on your requirement. Refer the following link.

https://github.com/SridharSathaSivam/ej2-rollup-demo 

Thanks,
Sridhar S

**Comment by vegarringdal** [comment]
@SridharSathaSivam @bharathm03 

Have there been done no check of sizes ?
Some of these will probably by big, but you also get a lot of features.
Would be nice if you have a map of sizes each module was in minified es6 gzip and unzipped in the docs.

Btw, love the community license. :+1:
