### ISSUE TITLE
fonts.googleapis.com not secure

### ISSUE THREAD

**Issue by jchilde** [syncfusion/ej2#9]
It appears that EJ2 uses "http://fonts.googleapis.com/css?family=Roboto:400,500"
This is creating a problem when developing from chrome with a https schema.

I would think that Https will always work, while http will not.

**Comment by ajithr** [comment]
Hi @jchilde,

Thanks for your interest in Essential JS 2. We will resolve the issue 'Roboto font failed to load in https schema' and the fix will be available at the end of this week.

Regards,
Ajith R

**Comment by SridharSathaSivam** [comment]
Hi @jchilde,

Thanks for the patience, We have fixed the issue ‘Roboto font failed to load in https schema’ from the 15.4.17 version and it is available in npm.

Thanks,
Sridhar S
